spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/task_db?sslmode=disable
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:change-me}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:change-me}
